export const SET_IMAGES = "SET_IMAGES"
export const SET_SINGLE_CHOSEN_IMG = "SET_SINGLE_CHOSEN_IMG"
export const SET_SINGLE_CHOSEN_IMG_FILE = "SET_SINGLE_CHOSEN_IMG_FILE"
export const SET_CHOSEN_IMG_DESC = "SET_CHOSEN_IMG_DESC"
export const SET_EXTRACTED_FACE_BOXES = "SET_EXTRACTED_FACE_BOXES"
export const SWITCH_LOADER = "SWITCH_LOADER"
export const SET_PREPROCESSING_STATUS = "SET_PREPROCESSING_STATUS"

